# HEADER PLACE HOLDER

from TupleTwo import *
from DictionaryTwo import *

__all__ = [
    'GemCraftingMaterialsOrder',
    'GemDusts',
    'GemDustsOrder',
    'GemGemsOrder',
    'GemHotkeyValues',
    'GemLiquids',
    'GemLiquidsOrder',
    'GemNames',
    'GemSuffixName',
    'ImbuePoints',
    'OverChargePercentages',
    'QualityModifiers',
]

GemSuffixName = d2({
    'Stat': 'Essence Jewel',
    'Resist': 'Shielding Jewel',
    'Hits': 'Essence Jewel',
    'Power': 'Essence Jewel',
    'Focus': '',
    'Skill': '',
})

GemNames = t2((
    'Raw',
    'Uncut',
    'Rough',
    'Flawed',
    'Imperfect',
    'Polished',
    'Faceted',
    'Precious',
    'Flawless',
    'Perfect',
))

GemGemsOrder = t2((
    'Lo',
    'Um',
    'On',
    'Ee',
    'Pal',
    'Mon',
    'Ros',
    'Zo',
    'Kath',
    'Ra',
))

GemLiquids = d2({
    'Fiery': 'Draconic Fire',
    'Earthen': 'Treant Blood',
    'Vapor': 'Swamp Fog',
    'Airy': 'Air Elemental Essence',
    'Heated': 'Heat From an Unearthly Pyre',
    'Icy': 'Frost From a Wasteland',
    'Watery': 'Leviathan Blood',
    'Dusty': 'Undead Ash and Holy Water',
    'Fire': 'Draconic Fire',
    'Earth': 'Treant Blood',
    'Vapor': 'Swamp Fog',
    'Air': 'Air Elemental Essence',
    'Heat': 'Heat From an Unearthly Pyre',
    'Ice': 'Frost From a Wasteland',
    'Water': 'Leviathan Blood',
    'Dust': 'Undead Ash and Holy Water',
    'Ashen': 'Undead Ash and Holy Water',
    'Vacuous': 'Swamp Fog',
    'Salt Crusted': 'Mystic Energy',
    'Steaming Spell': 'Swamp Fog',
    'Steaming Nature': 'Swamp Fog',
    'Steaming Fervor': 'Heat From an Unearthly Pyre',
    'Oozing': 'Treant Blood',
    'Mineral Encrusted': 'Heat From an Unearthly Pyre',
    'Lightning Charged': 'Leviathan Blood',
    'Molten Magma': 'Leviathan Blood',
    'Light': 'Sun Light',
    'Blood': 'Giant Blood',
    'Mystical': 'Mystic Energy',
    'Mystic': 'Mystic Energy',
    'Brilliant': ('Draconic Fire', 'Mystic Energy', 'Treant Blood'),
    'Finesse': ('Draconic Fire', 'Mystic Energy', 'Treant Blood'),
    'Ethereal Spell': 'Swamp Fog',
    'Phantasmal Spell': 'Leviathan Blood',
    'Spectral Spell': 'Draconic Fire',
    'Ethereal Arcane': 'Leviathan Blood',
    'Phantasmal Arcane': 'Draconic Fire',
    'Spectral Arcane': 'Air Elemental Essence',
    'Aberrant': 'Treant Blood',
    'Embracing': 'Frost From a Wasteland',
    'Shadowy': 'Swamp Fog',
    'Blighted Primal': 'Air Elemental Essence',
    'Blighted Rune': 'Undead Ash and Holy Water',
    'Valiant': 'Swamp Fog',
    'Unholy': 'Air Elemental Essence',
    'Glacial': 'Frost From a Wasteland',
    'Cinder': 'Draconic Fire',
    'Radiant': 'Sun Light',
    'Magnetic': 'Mystic Energy',
    'Clout': 'Giant Blood',
})

GemLiquidsOrder = (
    'Air Elemental Essence',
    'Draconic Fire',
    'Frost From a Wasteland',
    'Giant Blood',
    'Heat From an Unearthly Pyre',
    'Leviathan Blood',
    'Mystic Energy',
    'Sun Light',
    'Swamp Fog',
    'Treant Blood',
    'Undead Ash and Holy Water',
)

GemDusts = d2({
    'Essence Jewel': 'Essence of Life',
    'Shielding Jewel': 'Ground Draconic Scales',
    'Spell Stone': 'Ground Draconic Scales',
    'Sigil': 'Ground Draconic Scales',
    'Rune': 'Ground Draconic Scales',
    'Chaos Rune': 'Soot From Niflheim',
    'Battle Jewel': 'Bloodied Battlefield Dirt',
    'War Rune': 'Ground Giant Bone',
    'Primal Rune': 'Ground Vendo Bone',
    'Evocation Sigil': 'Ground Cave Crystal',
    'Fervor Sigil': 'Ground Blessed Undead Bone',
    'War Sigil': 'Ground Caer Stone',
    'Nature Spell Stone': 'Fairy Dust',
    'War Spell Stone': 'Unseelie Dust',
    'Arcane Spell Stone': 'Other Worldly Dust',
})

GemDustsOrder = (
    'Bloodied Battlefield Dirt',
    'Essence of Life',
    'Fairy Dust',
    'Ground Blessed Undead Bone',
    'Ground Caer Stone',
    'Ground Cave Crystal',
    'Ground Draconic Scales',
    'Ground Giant Bone',
    'Ground Vendo Bone',
    'Other Worldly Dust',
    'Soot From Niflheim',
    'Unseelie Dust',
)

GemCraftingMaterialsOrder = t2(
    GemGemsOrder
    + GemLiquidsOrder
    + GemDustsOrder
)

GemHotkeyValues = d2({

    'Albion': d2({

        'Fiery Essence Jewel': 0,
        'Earthen Essence Jewel': 2,
        'Vapor Essence Jewel': 4,
        'Airy Essence Jewel': 6,
        'Watery Essence Jewel': 8,
        'Heated Essence Jewel': 10,
        'Dusty Essence Jewel': 12,
        'Icy Essence Jewel': 14,
        'Earthen Shielding Jewel': 16,
        'Icy Shielding Jewel': 18,
        'Heated Shielding Jewel': 20,
        'Light Shielding Jewel': 22,
        'Airy Shielding Jewel': 24,
        'Vapor Shielding Jewel': 26,
        'Dusty Shielding Jewel': 28,
        'Fiery Shielding Jewel': 30,
        'Watery Shielding Jewel': 32,
        'Vapor Battle Jewel': 34,
        'Fiery Battle Jewel': 36,
        'Earthen Battle Jewel': 38,
        'Airy Battle Jewel': 40,
        'Dusty Battle Jewel': 42,
        'Heated Battle Jewel': 44,
        'Watery War Sigil': 46,
        'Fiery War Sigil': 48,
        'Dusty War Sigil': 50,
        'Heated War Sigil': 52,
        'Earthen War Sigil': 54,
        'Airy War Sigil': 56,
        'Vapor War Sigil': 58,
        'Icy War Sigil': 60,
        'Fiery Fervor Sigil': 62,
        'Airy Fervor Sigil': 64,
        'Watery Fervor Sigil': 66,
        'Earthen Fervor Sigil': 68,
        'Vapor Fervor Sigil': 70,
        'Earthen Evocation Sigil': 72,
        'Icy Evocation Sigil': 74,
        'Fiery Evocation Sigil': 76,
        'Airy Evocation Sigil': 78,
        'Heated Evocation Sigil': 80,
        'Dusty Evocation Sigil': 82,
        'Vapor Evocation Sigil': 84,
        'Watery Evocation Sigil': 86,
        'Blood Essence Jewel': 88,
        'Mystical Essence Jewel': 90,
        'Earth Sigil': 92,
        'Ice Sigil': 94,
        'Fire Sigil': 96,
        'Air Sigil': 98,
        'Heat Sigil': 100,
        'Dust Sigil': 102,
        'Vapor Sigil': 104,
        'Water Sigil': 106,
        'Molten Magma War Sigil': 108,
        'Vacuous Fervor Sigil': 110,
        'Salt Crusted Fervor Sigil': 112,
        'Ashen Fervor Sigil': 114,
        'Steaming Fervor Sigil': 116,
        'Vacuous Sigil': 118,
        'Salt Crusted Sigil': 120,
        'Ashen Sigil': 122,
        'Brilliant Sigil': 124,
        'Finesse War Sigil': 126,
        'Finesse Fervor Sigil': 128,
        'Glacial War Sigil': 130,
        'Cinder War Sigil': 132,
        'Radiant Fervor Sigil': 134,
        'Magnetic Fervor Sigil': 136,
        'Clout Fervor Sigil': 138,
    }),

    'Hibernia': d2({

        'Fiery Essence Jewel': 0,
        'Earthen Essence Jewel': 2,
        'Vapor Essence Jewel': 4,
        'Airy Essence Jewel': 6,
        'Watery Essence Jewel': 8,
        'Heated Essence Jewel': 10,
        'Dusty Essence Jewel': 12,
        'Icy Essence Jewel': 14,
        'Earthen Shielding Jewel': 16,
        'Icy Shielding Jewel': 18,
        'Heated Shielding Jewel': 20,
        'Light Shielding Jewel': 22,
        'Airy Shielding Jewel': 24,
        'Vapor Shielding Jewel': 26,
        'Dusty Shielding Jewel': 28,
        'Fiery Shielding Jewel': 30,
        'Watery Shielding Jewel': 32,
        'Vapor Battle Jewel': 34,
        'Fiery Battle Jewel': 36,
        'Earthen Battle Jewel': 38,
        'Airy Battle Jewel': 40,
        'Dusty Battle Jewel': 42,
        'Heated Battle Jewel': 44,
        'Watery War Spell Stone': 46,
        'Fiery War Spell Stone': 48,
        'Dusty War Spell Stone': 50,
        'Heated War Spell Stone': 52,
        'Earthen War Spell Stone': 54,
        'Icy War Spell Stone': 56,
        'Airy War Spell Stone': 58,
        'Fiery Nature Spell Stone': 60,
        'Watery Nature Spell Stone': 62,
        'Earthen Nature Spell Stone': 64,
        'Airy Nature Spell Stone': 66,
        'Airy Arcane Spell Stone': 68,
        'Fiery Arcane Spell Stone': 70,
        'Watery Arcane Spell Stone': 72,
        'Vapor Arcane Spell Stone': 74,
        'Icy Arcane Spell Stone': 76,
        'Earthen Arcane Spell Stone': 78,
        'Blood Essence Jewel': 80,
        'Mystical Essence Jewel': 82,
        'Fire Spell Stone': 84,
        'Water Spell Stone': 86,
        'Vapor Spell Stone': 88,
        'Ice Spell Stone': 90,
        'Earth Spell Stone': 92,
        'Light War Spell Stone': 94,
        'Steaming Nature Spell Stone': 96,
        'Oozing Nature Spell Stone': 98,
        'Mineral Encrusted Nature Spell Stone': 100,
        'Steaming Spell Stone': 102,
        'Oozing Spell Stone': 104,
        'Mineral Encrusted Spell Stone': 106,
        'Spectral Spell Stone': 108,
        'Phantasmal Spell Stone': 110,
        'Ethereal Spell Stone': 112,
        'Spectral Arcane Spell Stone': 114,
        'Phantasmal Arcane Spell Stone': 116,
        'Ethereal Arcane Spell Stone': 118,
        'Shadowy Arcane Spell Stone': 120,
        'Embracing Arcane Spell Stone': 122,
        'Aberrant Arcane Spell Stone': 124,
        'Brilliant Spell Stone': 126,
        'Finesse War Spell Stone': 128,
        'Finesse Nature Spell Stone': 130,
        'Glacial War Spell Stone': 132,
        'Cinder War Spell Stone': 134,
        'Radiant Nature Spell Stone': 136,
        'Magnetic Nature Spell Stone': 138,
        'Clout Nature Spell Stone': 140,
    }),

    'Midgard': d2({

        'Fiery Essence Jewel': 0,
        'Earthen Essence Jewel': 2,
        'Vapor Essence Jewel': 4,
        'Airy Essence Jewel': 6,
        'Watery Essence Jewel': 8,
        'Heated Essence Jewel': 10,
        'Dusty Essence Jewel': 12,
        'Icy Essence Jewel': 14,
        'Earthen Shielding Jewel': 16,
        'Icy Shielding Jewel': 18,
        'Heated Shielding Jewel': 20,
        'Light Shielding Jewel': 22,
        'Airy Shielding Jewel': 24,
        'Vapor Shielding Jewel': 26,
        'Dusty Shielding Jewel': 28,
        'Fiery Shielding Jewel': 30,
        'Watery Shielding Jewel': 32,
        'Vapor Battle Jewel': 34,
        'Fiery Battle Jewel': 36,
        'Earthen Battle Jewel': 38,
        'Airy Battle Jewel': 40,
        'Dusty Battle Jewel': 42,
        'Heated Battle Jewel': 44,
        'Watery War Rune': 46,
        'Fiery War Rune': 48,
        'Earthen War Rune': 50,
        'Heated War Rune': 52,
        'Airy War Rune': 54,
        'Vapor War Rune': 56,
        'Icy War Rune': 58,
        'Earthen Primal Rune': 60,
        'Airy Primal Rune': 62,
        'Fiery Primal Rune': 64,
        'Icy Chaos Rune': 66,
        'Dusty Chaos Rune': 68,
        'Heated Chaos Rune': 70,
        'Vapor Chaos Rune': 72,
        'Watery Chaos Rune': 74,
        'Airy Chaos Rune': 76,
        'Fiery Chaos Rune': 78,
        'Blood Essence Jewel': 82,
        'Mystical Essence Jewel': 84,
        'Ice Rune': 86,
        'Dust Rune': 88,
        'Heat Rune': 90,
        'Vapor Rune': 92,
        'Lightning Charged War Rune': 94,
        'Ashen Primal Rune': 96,
        'Ashen Rune': 98,
        'Blighted Rune': 100,
        'Valiant Primal Rune': 104,
        'Blighted Primal Rune': 106,
        'Unholy Primal Rune': 108,
        'Brilliant Rune': 110,
        'Finesse War Rune': 112,
        'Finesse Primal Rune': 114,
        'Glacial War Rune': 116,
        'Cinder War Rune': 118,
        'Radiant Primal Rune': 120,
        'Magnetic Primal Rune': 122,
        'Clout Primal Rune': 124,
    }),
})

OverChargePercentages = (
    0,
    10,
    20,
    30,
    50,
    70,
)

QualityModifiers = d2({
    '94': 0,
    '95': 0,
    '96': 6,
    '97': 8,
    '98': 10,
    '99': 18,
    '100': 26,
})

ImbuePoints = (
    1, 2, 2, 3, 4, 4, 5, 5, 6, 7,
    7, 8, 9, 9, 10, 10, 11, 12, 12, 13,
    13, 14, 15, 15, 16, 16, 17, 18, 18, 19,
    20, 20, 21, 21, 22, 23, 23, 24, 24, 25,
    26, 26, 27, 27, 28, 29, 29, 30, 31, 31, 32,
)

if __name__ == "__main__":
    pass
